### ISSUE TITLE
Use AppImage recipes

### ISSUE THREAD

**Issue by probonopd** [tomascw/tms-appimages#1]
Thanks for making an AppImage for LiteIDE.

Generally, the preferred way is for AppImages to be made by the upstream application authors in their release process, e.g., in the continuous build pipeline. There are [many examples](https://github.com/search?q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&utf8=%E2%9C%93) of projects which do that.

Second best is to write a recipe that converts pre-existing, upstrem-provided binary packages into an AppImage. A yml recipe makes AppImage generation reproducible. There are many examples at https://github.com/probonopd/AppImages/tree/master/recipes/meta.

I went ahead and converted your example to a yml recipe, which looks like this:

```
app: LiteIDE

ingredients:
  script:
    - wget -q https://sourceforge.net/projects/liteide/files/ -O - | grep "stats/timeline" | head -n 1 | cut -d "/" -f 5 > VERSION
    - VERSION=$(cat VERSION)
    - VERSION_NO_X=$(cat VERSION | sed -e 's|X||g')
    - wget -c "https://sourceforge.net/projects/liteide/files/${VERSION}/liteidex${VERSION_NO_X}.linux64-qt4.tar.bz2/download" --trust-server-names

script:
  - wget -c https://github.com/visualfc/liteide/raw/master/liteidex/liteide.desktop
  - wget -c https://github.com/visualfc/liteide/raw/master/liteidex/liteide.png
  - tar xf ../liteide*.tar.bz2 -C usr/ --strip 1
```

That's all that's needed. Note that no versions are hardcoded, so it will always produce the latest version. You can run it using the yml [recipe runner](https://github.com/probonopd/AppImages/blob/master/recipes/meta/Recipe).

You can find my AppImage generated with this recipe at
https://bintray.com/probono/AppImages/LiteIDE/_latestVersion#files.

So, I invite you to write those yml recipes, it's fun, fast, and easy.

**Comment by tomascw** [comment]
Thank you. I wasn't sure weather to use .yml recipes or not. My previous attempt was with the scripts.

**Comment by probonopd** [comment]
As you can see, the recipe approach scripts away much of the boilerplate code for you.
